<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $cities = [
            // Sindh Cities
            ['city_name' => 'Karachi', 'city_code' => 'KHI', 'status' => true],
            ['city_name' => 'Hyderabad', 'city_code' => 'HDD', 'status' => true],
            ['city_name' => 'Hub', 'city_code' => 'HUB', 'status' => true],
            ['city_name' => 'Thatta', 'city_code' => 'THT', 'status' => true],
            ['city_name' => 'Ahmedpur Lamma', 'city_code' => 'APL', 'status' => true],
            ['city_name' => 'Badin', 'city_code' => 'BDN', 'status' => true],
            ['city_name' => 'Dera Allah Yar', 'city_code' => 'DAY', 'status' => true],
            ['city_name' => 'Dadu', 'city_code' => 'DDU', 'status' => true],
            ['city_name' => 'Digri', 'city_code' => 'DIG', 'status' => true],
            ['city_name' => 'Daharki', 'city_code' => 'DKI', 'status' => true],
            ['city_name' => 'Dera Murad Jamali', 'city_code' => 'DMJ', 'status' => true],
            ['city_name' => 'Gambat', 'city_code' => 'GBT', 'status' => true],
            ['city_name' => 'Ghotki', 'city_code' => 'GTI', 'status' => true],
            ['city_name' => 'Jacobabad', 'city_code' => 'JCB', 'status' => true],
            ['city_name' => 'Khan Bela', 'city_code' => 'NBA', 'status' => true],
            ['city_name' => 'Khairpur Mirs', 'city_code' => 'KHM', 'status' => true],
            ['city_name' => 'Kandh Kot', 'city_code' => 'KKK', 'status' => true],
            ['city_name' => 'Kandiaro', 'city_code' => 'KDR', 'status' => true],
            ['city_name' => 'Kunri', 'city_code' => 'KNI', 'status' => true],
            ['city_name' => 'K.n. Shah', 'city_code' => 'KNS', 'status' => true],
            ['city_name' => 'Larkana', 'city_code' => 'LAR', 'status' => true],
            ['city_name' => 'Mehar', 'city_code' => 'MHR', 'status' => true],
            ['city_name' => 'Mitiari', 'city_code' => 'MIT', 'status' => true],
            ['city_name' => 'Mirpur Khas', 'city_code' => 'MPK', 'status' => true],
            ['city_name' => 'Mirpur Mathelo', 'city_code' => 'MPM', 'status' => true],
            ['city_name' => 'Matiari', 'city_code' => 'MRI', 'status' => true],
            ['city_name' => 'Moro', 'city_code' => 'MRO', 'status' => true],
            ['city_name' => 'Mehrabpur', 'city_code' => 'MRB', 'status' => true],
            ['city_name' => 'Noudero', 'city_code' => 'NRO', 'status' => true],
            ['city_name' => 'Noshero Feroze', 'city_code' => 'NFZ', 'status' => true],
            ['city_name' => 'Khan Pur', 'city_code' => 'NPR', 'status' => true],
            ['city_name' => 'Pani Aqil', 'city_code' => 'PNQ', 'status' => true],
            ['city_name' => 'Ranipur', 'city_code' => 'RNP', 'status' => true],
            ['city_name' => 'Rahimyar Khan', 'city_code' => 'RYK', 'status' => true],
            ['city_name' => 'Sanghar', 'city_code' => 'SAN', 'status' => true],
            ['city_name' => 'Sadiq Abad', 'city_code' => 'SQD', 'status' => true],
            ['city_name' => 'Shikarpur', 'city_code' => 'SIP', 'status' => true],
            ['city_name' => 'Sukkar', 'city_code' => 'SKZ', 'status' => true],
            ['city_name' => 'Shahdadpur', 'city_code' => 'SHP', 'status' => true],
            ['city_name' => 'Tando Allah Yar', 'city_code' => 'TDY', 'status' => true],
            ['city_name' => 'Tando Jam', 'city_code' => 'TDJ', 'status' => true],
            ['city_name' => 'Tando Adam', 'city_code' => 'TDA', 'status' => true],
            ['city_name' => 'Tando Muhammad Khan', 'city_code' => 'TMK', 'status' => true],
            ['city_name' => 'Quetta', 'city_code' => 'UET', 'status' => true],
            ['city_name' => 'Umer Kot', 'city_code' => 'UMK', 'status' => true],
            ['city_name' => 'Ubaro', 'city_code' => 'UBR', 'status' => true],
            ['city_name' => 'Usta Muhammad', 'city_code' => 'UST', 'status' => true],
            ['city_name' => 'Nawab Shah', 'city_code' => 'WNS', 'status' => true],
            ['city_name' => 'Zahir Peer', 'city_code' => 'ZPR', 'status' => true],

            // Punjab Cities
            ['city_name' => 'Lahore', 'city_code' => 'LHE', 'status' => true],
            ['city_name' => 'Arifwala', 'city_code' => 'AFA', 'status' => true],
            ['city_name' => 'Abdul Hakeem', 'city_code' => 'AKM', 'status' => true],
            ['city_name' => 'Bahawalpur', 'city_code' => 'BHV', 'status' => true],
            ['city_name' => 'Bhakkar', 'city_code' => 'BKK', 'status' => true],
            ['city_name' => 'Bhai Pheru', 'city_code' => 'BPR', 'status' => true],
            ['city_name' => 'Burewala', 'city_code' => 'BRW', 'status' => true],
            ['city_name' => 'Chichawatni', 'city_code' => 'CCW', 'status' => true],
            ['city_name' => 'Chishtian', 'city_code' => 'CHT', 'status' => true],
            ['city_name' => 'Dera Ismail Khan', 'city_code' => 'DIK', 'status' => true],
            ['city_name' => 'Faisalabad', 'city_code' => 'LYP', 'status' => true],
            ['city_name' => 'Haroonabad', 'city_code' => 'HRN', 'status' => true],
            ['city_name' => 'Hasil Pur', 'city_code' => 'HSL', 'status' => true],
            ['city_name' => 'Jhang', 'city_code' => 'JHG', 'status' => true],
            ['city_name' => 'Jauharabad', 'city_code' => 'JRD', 'status' => true],
            ['city_name' => 'Kabirwala', 'city_code' => 'KBW', 'status' => true],
            ['city_name' => 'Kala Shah Kaku', 'city_code' => 'KSK', 'status' => true],
            ['city_name' => 'Kasur', 'city_code' => 'KSR', 'status' => true],
            ['city_name' => 'Khanewal', 'city_code' => 'KWL', 'status' => true],
            ['city_name' => 'Minchanaabad', 'city_code' => 'MHN', 'status' => true],
            ['city_name' => 'Mian Channu', 'city_code' => 'MCN', 'status' => true],
            ['city_name' => 'Muridkay', 'city_code' => 'MRY', 'status' => true],
            ['city_name' => 'Multan', 'city_code' => 'MUX', 'status' => true],
            ['city_name' => 'Mianwali', 'city_code' => 'MWI', 'status' => true],
            ['city_name' => 'Bahwalnagar', 'city_code' => 'NGR', 'status' => true],
            ['city_name' => 'Okara', 'city_code' => 'OKR', 'status' => true],
            ['city_name' => 'Pattoke', 'city_code' => 'PTI', 'status' => true],
            ['city_name' => 'Raiwind', 'city_code' => 'RND', 'status' => true],
            ['city_name' => 'Sargodha', 'city_code' => 'SGD', 'status' => true],
            ['city_name' => 'Sheikhupura', 'city_code' => 'SPA', 'status' => true],
            ['city_name' => 'Sundar', 'city_code' => 'SDR', 'status' => true],
            ['city_name' => 'Sahiwal', 'city_code' => 'SWL', 'status' => true],
            ['city_name' => 'Vehari', 'city_code' => 'VRI', 'status' => true],
            ['city_name' => 'Alipur', 'city_code' => 'APR', 'status' => true],
            ['city_name' => 'Ahmedpur East', 'city_code' => 'APE', 'status' => true],
            ['city_name' => 'Rabwah', 'city_code' => 'AWH', 'status' => true],
            ['city_name' => 'Basirpur', 'city_code' => 'BSP', 'status' => true],
            ['city_name' => 'Dera Ghazi Khan', 'city_code' => 'DGK', 'status' => true],
            ['city_name' => 'Depalpur', 'city_code' => 'DPR', 'status' => true],
            ['city_name' => 'Dunia Pur', 'city_code' => 'DNP', 'status' => true],
            ['city_name' => 'Fort Abbass', 'city_code' => 'FAB', 'status' => true],
            ['city_name' => 'Ferozwatowan', 'city_code' => 'FTN', 'status' => true],
            ['city_name' => 'Gaggo Mandi', 'city_code' => 'GMD', 'status' => true],
            ['city_name' => 'Hujra Shah Mukeem', 'city_code' => 'HHM', 'status' => true],
            ['city_name' => 'Iskandarabad', 'city_code' => 'ISK', 'status' => true],
            ['city_name' => 'Chiniot', 'city_code' => 'IOT', 'status' => true],
            ['city_name' => 'Jampur', 'city_code' => 'JMR', 'status' => true],
            ['city_name' => 'Jalalpur Pirwala', 'city_code' => 'JPP', 'status' => true],
            ['city_name' => 'Jaranwala', 'city_code' => 'JWA', 'status' => true],
            ['city_name' => 'Kala Bagh', 'city_code' => 'KBG', 'status' => true],
            ['city_name' => 'Kahuta', 'city_code' => 'KHT', 'status' => true],
            ['city_name' => 'Kamalia', 'city_code' => 'KML', 'status' => true],
            ['city_name' => 'Kameer', 'city_code' => 'KMR', 'status' => true],
            ['city_name' => 'Kot Addu', 'city_code' => 'KOT', 'status' => true],
            ['city_name' => 'Kot Momin', 'city_code' => 'KTM', 'status' => true],
            ['city_name' => 'Lodhran', 'city_code' => 'LOD', 'status' => true],
            ['city_name' => 'Layya', 'city_code' => 'LYY', 'status' => true],
            ['city_name' => 'Muzaffar Gargh', 'city_code' => 'MZG', 'status' => true],
            ['city_name' => 'Piplan', 'city_code' => 'PPN', 'status' => true],
            ['city_name' => 'Pir Mahal', 'city_code' => 'PML', 'status' => true],
            ['city_name' => 'Pak Pattan Sharif', 'city_code' => 'PPS', 'status' => true],
            ['city_name' => 'Rajanpur', 'city_code' => 'RJP', 'status' => true],
            ['city_name' => 'Renala Khurd', 'city_code' => 'RLK', 'status' => true],
            ['city_name' => 'Gojra', 'city_code' => 'RRA', 'status' => true],
            ['city_name' => 'Khushab', 'city_code' => 'SAB', 'status' => true],
            ['city_name' => 'Samundri', 'city_code' => 'SAM', 'status' => true],
            ['city_name' => 'Shuja Abad', 'city_code' => 'SHJ', 'status' => true],
            ['city_name' => 'Sangla Hills', 'city_code' => 'SHL', 'status' => true],
            ['city_name' => 'Chashma', 'city_code' => 'CMA', 'status' => true],
            ['city_name' => 'Sillanwali', 'city_code' => 'SLW', 'status' => true],
            ['city_name' => 'Shorkot', 'city_code' => 'SQT', 'status' => true],
            ['city_name' => 'Tobe Tek Singh', 'city_code' => 'TTS', 'status' => true],
            ['city_name' => 'Tandiliyawala', 'city_code' => 'TDW', 'status' => true],
            ['city_name' => 'Wahn Bachran', 'city_code' => 'WBN', 'status' => true],
            ['city_name' => 'Yazman', 'city_code' => 'YZM', 'status' => true],
            ['city_name' => 'Rawalpindi', 'city_code' => 'RWP', 'status' => true],
            ['city_name' => 'Islamabad', 'city_code' => 'ISB', 'status' => true],

            // KPK Cities
            ['city_name' => 'Abbottabad', 'city_code' => 'ABT', 'status' => true],
            ['city_name' => 'Chakwal', 'city_code' => 'CKL', 'status' => true],
            ['city_name' => 'Daska', 'city_code' => 'DSK', 'status' => true],
            ['city_name' => 'Gujrat', 'city_code' => 'GRT', 'status' => true],
            ['city_name' => 'Gujranwala', 'city_code' => 'GUJ', 'status' => true],
            ['city_name' => 'Jhelum', 'city_code' => 'JLM', 'status' => true],
            ['city_name' => 'Kamoke', 'city_code' => 'KMK', 'status' => true],
            ['city_name' => 'Kharian', 'city_code' => 'KRN', 'status' => true],
            ['city_name' => 'Mandi Baha Uddin', 'city_code' => 'MBD', 'status' => true],
            ['city_name' => 'Nowshera', 'city_code' => 'NOW', 'status' => true],
            ['city_name' => 'Peshawar', 'city_code' => 'PEW', 'status' => true],
            ['city_name' => 'Mirpur Ak', 'city_code' => 'QML', 'status' => true],
            ['city_name' => 'Sialkot', 'city_code' => 'SKT', 'status' => true],
            ['city_name' => 'Wah', 'city_code' => 'WAH', 'status' => true],
            ['city_name' => 'Wazirabad', 'city_code' => 'WZD', 'status' => true],
            ['city_name' => 'Attock', 'city_code' => 'ATT', 'status' => true],
            ['city_name' => 'Charsadda', 'city_code' => 'CSD', 'status' => true],
            ['city_name' => 'Chawinda', 'city_code' => 'CWD', 'status' => true],
            ['city_name' => 'Daud Khel', 'city_code' => 'DDK', 'status' => true],
            ['city_name' => 'Dina', 'city_code' => 'DIN', 'status' => true],
            ['city_name' => 'Fateh Jang', 'city_code' => 'FTG', 'status' => true],
            ['city_name' => 'Guddu', 'city_code' => 'GDN', 'status' => true],
            ['city_name' => 'Gujran Khan', 'city_code' => 'GKN', 'status' => true],
            ['city_name' => 'Hafizabad', 'city_code' => 'HZD', 'status' => true],
            ['city_name' => 'Lala Musa', 'city_code' => 'LLM', 'status' => true],
            ['city_name' => 'Muzaffarabad', 'city_code' => 'MAK', 'status' => true],
            ['city_name' => 'Mardan', 'city_code' => 'MDN', 'status' => true],
            ['city_name' => 'Narowal', 'city_code' => 'NRL', 'status' => true],
            ['city_name' => 'Kohat', 'city_code' => 'OHT', 'status' => true],
            ['city_name' => 'Pind Dadan Khan', 'city_code' => 'PDK', 'status' => true],
            ['city_name' => 'Pasroor', 'city_code' => 'PRR', 'status' => true],
            ['city_name' => 'Murree', 'city_code' => 'REE', 'status' => true],
            ['city_name' => 'Shakargarh', 'city_code' => 'SGR', 'status' => true],
            ['city_name' => 'Swat', 'city_code' => 'SWT', 'status' => true],
            ['city_name' => 'Talagang', 'city_code' => 'TLG', 'status' => true],
            ['city_name' => 'Bhimber', 'city_code' => 'BMR', 'status' => true],
            ['city_name' => 'Dinga', 'city_code' => 'DNG', 'status' => true],
            ['city_name' => 'Dadyal Ak', 'city_code' => 'DDL', 'status' => true],
            ['city_name' => 'Gakhar Mandi', 'city_code' => 'GKM', 'status' => true],
            ['city_name' => 'Hari Pur', 'city_code' => 'HRI', 'status' => true],
            ['city_name' => 'Hassanabdal', 'city_code' => 'HSN', 'status' => true],
            ['city_name' => 'Hattar', 'city_code' => 'HTR', 'status' => true],
            ['city_name' => 'Hawilian', 'city_code' => 'HVL', 'status' => true],
            ['city_name' => 'Hazro', 'city_code' => 'HAZ', 'status' => true],
            ['city_name' => 'Jalalpur Jattan', 'city_code' => 'JJT', 'status' => true],
            ['city_name' => 'Kotly Ak', 'city_code' => 'KOL', 'status' => true],
            ['city_name' => 'Kamra', 'city_code' => 'KAM', 'status' => true],
            ['city_name' => 'Mangla', 'city_code' => 'MGL', 'status' => true],
            ['city_name' => 'Mansahra', 'city_code' => 'MNA', 'status' => true],
            ['city_name' => 'Nowshera Virka', 'city_code' => 'NOV', 'status' => true],
            ['city_name' => 'Phalia', 'city_code' => 'PLA', 'status' => true],
            ['city_name' => 'Qila Deedar Singh', 'city_code' => 'QDS', 'status' => true],
            ['city_name' => 'Rawat', 'city_code' => 'RWT', 'status' => true],
            ['city_name' => 'Sara-e-alamgir', 'city_code' => 'SIR', 'status' => true],
            ['city_name' => 'Sawabi', 'city_code' => 'SWB', 'status' => true],
            ['city_name' => 'Topi', 'city_code' => 'TOP', 'status' => true],
            ['city_name' => 'Tarbela', 'city_code' => 'TRB', 'status' => true],
            ['city_name' => 'Taxila', 'city_code' => 'TXL', 'status' => true],
            ['city_name' => 'Zafarwal', 'city_code' => 'ZFL', 'status' => true],
            ['city_name' => 'Liaqat Pur', 'city_code' => 'LQR', 'status' => true],
            ['city_name' => 'Rato Dero', 'city_code' => 'RTD', 'status' => true],
            ['city_name' => 'Khanpur Dem', 'city_code' => 'KPD', 'status' => true],
            ['city_name' => 'Khewra', 'city_code' => 'KEW', 'status' => true],
            ['city_name' => 'Alipur Chatta', 'city_code' => 'APC', 'status' => true],
            ['city_name' => 'Bhikky', 'city_code' => 'BHK', 'status' => true],
            ['city_name' => 'Daulatpur', 'city_code' => 'DLT', 'status' => true],
            ['city_name' => 'Donga Bonga', 'city_code' => 'DGB', 'status' => true],
            ['city_name' => 'Faqirwali', 'city_code' => 'FRW', 'status' => true],
            ['city_name' => 'Harappa', 'city_code' => 'HRP', 'status' => true],
            ['city_name' => 'Hattian', 'city_code' => 'HTN', 'status' => true],
            ['city_name' => 'Havali Lakhan', 'city_code' => 'HLK', 'status' => true],
            ['city_name' => 'Head Marala', 'city_code' => 'HDM', 'status' => true],
            ['city_name' => 'Jamshoro', 'city_code' => 'JSR', 'status' => true],
            ['city_name' => 'Jand', 'city_code' => 'JND', 'status' => true],
            ['city_name' => 'Jatlaan', 'city_code' => 'JTN', 'status' => true],
            ['city_name' => 'Jin Pur', 'city_code' => 'JIN', 'status' => true],
            ['city_name' => 'Kallar Kahar', 'city_code' => 'KKR', 'status' => true],
            ['city_name' => 'Kallar Saddiyian', 'city_code' => 'KSD', 'status' => true],
            ['city_name' => 'Klaske', 'city_code' => 'KLS', 'status' => true],
            ['city_name' => 'Malikwal', 'city_code' => 'MKL', 'status' => true],
            ['city_name' => 'Mandra', 'city_code' => 'MND', 'status' => true],
            ['city_name' => 'Manga Mandi', 'city_code' => 'MMD', 'status' => true],
            ['city_name' => 'Nooriabad', 'city_code' => 'NRD', 'status' => true],
            ['city_name' => 'Pindi Bhattiya', 'city_code' => 'PBT', 'status' => true],
            ['city_name' => 'Pindi Gheb', 'city_code' => 'PGB', 'status' => true],
            ['city_name' => 'Qamber Ali Khan', 'city_code' => 'QAK', 'status' => true],
            ['city_name' => 'Quaid Abad', 'city_code' => 'QBD', 'status' => true],
            ['city_name' => 'Rohri', 'city_code' => 'RHI', 'status' => true],
            ['city_name' => 'Sakhi Sarwar', 'city_code' => 'SIS', 'status' => true],
            ['city_name' => 'Satiayana', 'city_code' => 'STN', 'status' => true],
            ['city_name' => 'Sehwan Sharif', 'city_code' => 'SHN', 'status' => true],
            ['city_name' => 'Shahdara', 'city_code' => 'SHD', 'status' => true],
            ['city_name' => 'Shahpur Saddar', 'city_code' => 'SPS', 'status' => true],
            ['city_name' => 'Skrand', 'city_code' => 'SKN', 'status' => true],
            ['city_name' => 'Sohawa', 'city_code' => 'SOW', 'status' => true],
            ['city_name' => 'Tatlay Wali', 'city_code' => 'TTW', 'status' => true],
            ['city_name' => 'Taunsa Sharif', 'city_code' => 'TNS', 'status' => true],
            ['city_name' => 'Tranda Muhammad Pannah', 'city_code' => 'TMP', 'status' => true],
            ['city_name' => 'Ugoke', 'city_code' => 'UGI', 'status' => true],
            ['city_name' => 'Sanjarpur', 'city_code' => 'SJP', 'status' => true],
            ['city_name' => 'Jatoi', 'city_code' => 'JOT', 'status' => true],
            ['city_name' => 'Gadoon Amazai', 'city_code' => 'GDA', 'status' => true],
            ['city_name' => 'Esa Khel', 'city_code' => 'ESK', 'status' => true],
            ['city_name' => 'Kashmore', 'city_code' => 'KSM', 'status' => true],
            ['city_name' => 'Kotla Arab Ali Khan', 'city_code' => 'KRB', 'status' => true],
            ['city_name' => 'Mithi', 'city_code' => 'MTH', 'status' => true],
            ['city_name' => 'Melsi', 'city_code' => 'MLS', 'status' => true],
            ['city_name' => 'Sambrial', 'city_code' => 'SBR', 'status' => true],
            ['city_name' => 'Sumandari', 'city_code' => 'SML', 'status' => true],
            ['city_name' => 'Shahkot', 'city_code' => 'SHK', 'status' => true],
            ['city_name' => 'Shorekot Cantt', 'city_code' => 'SKC', 'status' => true],
            ['city_name' => 'Basti Shorekot', 'city_code' => 'BSK', 'status' => true],
            ['city_name' => 'Goth Machi', 'city_code' => 'GMI', 'status' => true],
            ['city_name' => 'Jahaniya', 'city_code' => 'JNA', 'status' => true],
            ['city_name' => 'Khyber', 'city_code' => 'KYR', 'status' => true],
            ['city_name' => 'Khurrianwala', 'city_code' => 'KRW', 'status' => true],
            ['city_name' => 'Kotly Loharana', 'city_code' => 'KLA', 'status' => true],
            ['city_name' => 'Sekhat', 'city_code' => 'SKH', 'status' => true],
            ['city_name' => 'Battagram', 'city_code' => 'BGR', 'status' => true],
            ['city_name' => 'Bannu', 'city_code' => 'BNP', 'status' => true],
            ['city_name' => 'Pallandri', 'city_code' => 'PLN', 'status' => true],
            ['city_name' => 'Gilgit', 'city_code' => 'GIL', 'status' => true],
            ['city_name' => 'Skardu', 'city_code' => 'SKD', 'status' => true],
            ['city_name' => 'Sibi', 'city_code' => 'SIB', 'status' => true],
        ];

        foreach ($cities as $city) {
            City::updateOrCreate(
                ['city_code' => $city['city_code']],
                $city
            );
        }
    }
}
