<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class LandingPageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ============================================================
        // 1. HERO SLIDES (3 entries)
        // ============================================================
        DB::table('hero_slides')->insert([
            [
                'title' => 'Shipping & Logistics Solution for <span class="text-primary">USA to Pakistan</span>',
                'subtitle' => 'Shipping & Logistics Solution',
                'content' => 'Fast, Reliable & Affordable Shipping from USA to Pakistan',
                'description' => 'Trusted by thousands of customers for secure package forwarding, consolidation, and door-to-door delivery across Pakistan.',
                'image' => 'hero/hero-1.jpg',
                'button1_text' => 'Get Started',
                'button1_link' => '/signup',
                'button2_text' => 'Free Quote',
                'button2_link' => '#contact',
                'order' => 1,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Your Personal <span class="text-primary">US Address</span> for Shopping',
                'subtitle' => 'Package Forwarding Made Easy',
                'content' => 'Shop from Any US Retailer & We\'ll Deliver to Your Doorstep in Pakistan',
                'description' => 'Get your free US shipping address today. Consolidate multiple packages and save up to 70% on international shipping.',
                'image' => 'hero/hero-2.jpg',
                'button1_text' => 'Get Your Address',
                'button1_link' => '/signup',
                'button2_text' => 'Learn More',
                'button2_link' => '#services',
                'order' => 2,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Trusted Logistics Partner for <span class="text-primary">Businesses</span>',
                'subtitle' => 'Commercial Import Solutions',
                'content' => 'End-to-End Supply Chain Management from USA to Pakistan',
                'description' => 'Customs brokerage, warehousing, and fulfillment solutions for eCommerce sellers, importers, and corporate enterprises.',
                'image' => 'hero/hero-3.jpg',
                'button1_text' => 'Contact Sales',
                'button1_link' => '#contact',
                'button2_text' => 'View Services',
                'button2_link' => '#services',
                'order' => 3,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 2. ABOUT SECTIONS (3 entries with features)
        // ============================================================
        DB::table('about_sections')->insert([
            [
                'title' => 'Quick Transport and Logistics Solutions',
                'subtitle' => 'About US2PK',
                'content' => 'US2PK connects Pakistan to the world\'s best products through trusted shopping, shipping, and delivery solutions. We handle everything from purchase to doorstep with precision, security, and efficiency. Our comprehensive logistics network combines advanced technology, experienced professionals, and trusted transportation partners to deliver every shipment with the highest standards of service.',
                'image' => 'about/about-us-1.jpg',
                'features' => json_encode([
                    ['icon' => 'fa fa-shopping-cart', 'title' => 'Shop US Stores', 'description' => 'Shop from US online stores and have eligible purchases sent to your US2PK receiving address.'],
                    ['icon' => 'fa fa-warehouse', 'title' => 'Delaware Warehouse', 'description' => 'US2PK has publicly been described as operating a warehouse in Delaware where online purchases are received before shipment to Pakistan.'],
                    ['icon' => 'fa fa-truck', 'title' => 'USA to Pakistan Delivery', 'description' => 'Packages are forwarded from the United States to customers across Pakistan.'],
                    ['icon' => 'fa fa-map-marker-alt', 'title' => 'Shipment Tracking', 'description' => 'Customers can track shipments and receive status updates during transportation.'],
                ]),
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'US2PK — A Cross-Border Shipping Service Since 2013',
                'subtitle' => 'Our Mission',
                'content' => 'US2PK was established in 2013 as a private USA-to-Pakistan delivery service. Publicly available company coverage describes US2PK as a business of Paradise Ecommerce Solutions (PES), part of Paradise Group. The service was built around giving customers a practical way to shop from US stores, receive purchases at a US warehouse in Delaware, and have them shipped safely to Pakistan. Our focus is simple: make cross-border shopping and delivery easier, more transparent, and more convenient for customers in Pakistan.',
                'image' => 'about/about-us-2.jpg',
                'features' => json_encode([
                    ['icon' => 'fa fa-calendar', 'title' => 'Established in 2013', 'description' => 'US2PK has been publicly described as established in 2013.'],
                    ['icon' => 'fa fa-map-pin', 'title' => 'Delaware Operations', 'description' => 'The Delaware location was selected as a receiving and forwarding point for US purchases.'],
                    ['icon' => 'fa fa-shopping-bag', 'title' => 'Online Shopping Support', 'description' => 'The service model lets customers shop from recognized US online stores and forward eligible purchases to Pakistan.'],
                    ['icon' => 'fa fa-search-location', 'title' => 'Track Your Shipment', 'description' => 'Shipment tracking and transport updates are part of the customer delivery experience.'],
                ]),
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Delivering Excellence Across Borders',
                'subtitle' => 'Our Vision',
                'content' => 'US2PK connects Pakistani customers with products available from US retailers. Customers can register, shop online, send purchases to their US2PK receiving address, and then arrange shipment to Pakistan. Public descriptions of the service identify a warehouse operation in Delaware and nationwide delivery in Pakistan, with shipment tracking and status updates available after dispatch.',
                'image' => 'about/about-us-3.jpg',
                'features' => json_encode([
                    ['icon' => 'fa fa-globe-asia', 'title' => 'Cross-Border Access', 'description' => 'Helping customers in Pakistan access products sold through the US online marketplace.'],
                    ['icon' => 'fa fa-box-open', 'title' => 'Receiving & Forwarding', 'description' => 'US purchases are received before being prepared for onward delivery to Pakistan.'],
                    ['icon' => 'fa fa-route', 'title' => 'End-to-End Visibility', 'description' => 'Tracking information helps customers follow their shipment after dispatch.'],
                    ['icon' => 'fa fa-home', 'title' => 'Nationwide Delivery', 'description' => 'Public company coverage describes US2PK as serving customers across Pakistan.'],
                ]),
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 3. SERVICES (6 entries)
        // ============================================================
        DB::table('services')->insert([
            [
                'title' => 'Air Freight',
                'subtitle' => 'US → PK · AIR',
                'content' => 'Fast and reliable air shipping from major US airports to all major cities in Pakistan. Ideal for urgent packages, electronics, fashion products, medical equipment, and high-value goods. Estimated delivery: 5–8 business days.',
                'image' => 'services/air-freight.jpg',
                'icon' => 'fas fa-plane',
                'link' => '#contact',
                'order' => 1,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ocean Freight',
                'subtitle' => 'US → PK · SEA',
                'content' => 'Cost‑effective sea freight for bulk shipments, containers, furniture, industrial machinery, and wholesale imports. We handle FCL and LCL shipments with full tracking and documentation. Estimated delivery: 30–45 days.',
                'image' => 'services/ocean-freight.jpg',
                'icon' => 'fas fa-ship',
                'link' => '#contact',
                'order' => 2,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Customs Clearance',
                'subtitle' => 'PK · LAND',
                'content' => 'We manage all customs documentation, duties, and taxes on your behalf. Our specialists handle HS code classification, duty estimation, customs declaration, and clearance coordination. Avoid delays and ensure smooth import clearance in Pakistan.',
                'image' => 'services/customs-clearance.jpg',
                'icon' => 'fas fa-file-invoice',
                'link' => '#contact',
                'order' => 3,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Package Consolidation',
                'subtitle' => 'CONSOLIDATION',
                'content' => 'Combine multiple purchases from different US retailers into one shipment to save on shipping costs. We professionally repack, optimize weight, and securely consolidate your items with barcode tracking and inventory verification.',
                'image' => 'services/consolidation.jpg',
                'icon' => 'fas fa-boxes',
                'link' => '#contact',
                'order' => 4,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Warehousing & Storage',
                'subtitle' => 'US WAREHOUSE',
                'content' => 'Safe, climate‑controlled warehouse storage in the USA and Pakistan. Services include package receiving, inventory management, barcode tracking, quality inspection, secure storage, and shipment preparation for both personal and commercial shipments.',
                'image' => 'services/warehousing.jpg',
                'icon' => 'fas fa-warehouse',
                'link' => '#contact',
                'order' => 5,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Door‑to‑Door Delivery',
                'subtitle' => 'LIVE STATUS',
                'content' => 'We pick up from your US supplier and deliver directly to your doorstep anywhere in Pakistan. Full tracking from pickup to delivery with professional handling at every stage. Includes supplier pickup, consolidation, shipping, customs clearance, and last-mile delivery.',
                'image' => 'services/door-to-door.jpg',
                'icon' => 'fas fa-truck',
                'link' => '#contact',
                'order' => 6,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 4. TESTIMONIALS (5 entries)
        // ============================================================
        DB::table('testimonials')->insert([
            [
                'name' => 'Ahmed Raza',
                'title' => 'eCommerce Business Owner',
                'content' => 'US2PK has transformed my business. I can now import products from the USA with confidence. Their consolidation service saved me over 40% on shipping costs, and their customs clearance team handled everything seamlessly. Highly recommended!',
                'image' => 'testimonials/ahmed-raza.jpg',
                'rating' => 5,
                'order' => 1,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sana Malik',
                'title' => 'Online Shopper',
                'content' => 'I love shopping from US brands but shipping was always a hassle. US2PK made it so easy! I got my US address, shopped from multiple stores, and they consolidated everything beautifully. My package arrived in perfect condition within 7 days.',
                'image' => 'testimonials/sana-malik.jpg',
                'rating' => 5,
                'order' => 2,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bilal Khan',
                'title' => 'Corporate Importer',
                'content' => 'We\'ve been using US2PK for our corporate imports for over two years. Their reliability, transparency, and customer service are unmatched. They handle our entire supply chain from US suppliers to our warehouse in Karachi. An invaluable logistics partner.',
                'image' => 'testimonials/bilal-khan.jpg',
                'rating' => 5,
                'order' => 3,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fatima Ali',
                'title' => 'Small Business Owner',
                'content' => 'As a small business owner, I was worried about the complexities of international shipping. US2PK made it simple and affordable. Their team guided me through every step, and my products arrive on time every single time.',
                'image' => 'testimonials/fatima-ali.jpg',
                'rating' => 5,
                'order' => 4,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Usman Chaudhry',
                'title' => 'Fashion Retailer',
                'content' => 'US2PK handles all our clothing imports from New York. Their consolidation service is excellent, and their team is always responsive. Our customers love the quick delivery times.',
                'image' => 'testimonials/usman-chaudhry.jpg',
                'rating' => 4,
                'order' => 5,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 5. TEAM MEMBERS (4 entries)
        // ============================================================
        DB::table('team_members')->insert([
            [
                'name' => 'Muhammad Usman',
                'position' => 'CEO & Founder',
                'bio' => 'With over 15 years of experience in international logistics and supply chain management, Muhammad Usman founded US2PK with a vision to simplify shipping from USA to Pakistan. His expertise in cross-border trade and customs regulations has made US2PK a trusted name in the industry.',
                'image' => 'team/ceo.jpg',
                'facebook' => '#',
                'twitter' => '#',
                'instagram' => '#',
                'linkedin' => '#',
                'order' => 1,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ali Hassan',
                'position' => 'Operations Manager',
                'bio' => 'Ali oversees day-to-day operations, ensuring smooth processing and timely delivery of all shipments. His expertise in logistics optimization has helped US2PK maintain high service standards and customer satisfaction across Pakistan.',
                'image' => 'team/operations-manager.jpg',
                'facebook' => '#',
                'twitter' => '#',
                'instagram' => '#',
                'linkedin' => '#',
                'order' => 2,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zara Ahmed',
                'position' => 'Customer Experience Lead',
                'bio' => 'Zara leads our customer support team with a focus on delivering exceptional service. She ensures every customer receives prompt and professional assistance throughout their shipping journey from the USA to Pakistan.',
                'image' => 'team/customer-lead.jpg',
                'facebook' => '#',
                'twitter' => '#',
                'instagram' => '#',
                'linkedin' => '#',
                'order' => 3,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Imran Khan',
                'position' => 'Customs Brokerage Specialist',
                'bio' => 'With deep knowledge of Pakistan customs regulations, Imran ensures your shipments clear customs smoothly and efficiently. He handles all documentation, compliance requirements, and works closely with customs authorities to avoid delays.',
                'image' => 'team/customs-specialist.jpg',
                'facebook' => '#',
                'twitter' => '#',
                'instagram' => '#',
                'linkedin' => '#',
                'order' => 4,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 6. PRICING PLANS (3 entries)
        // ============================================================
        DB::table('pricing_plans')->insert([
            [
                'title' => 'Personal Shipping',
                'section_title' => 'Shipping Options',
                'section_content' => 'Request a current quote for your USA-to-Pakistan shipment. Final pricing depends on shipment details and the selected service.',
                'price' => 'Quote',
                'interval' => 'Per Shipment',
                'features' => '<li><i class="fa fa-check text-primary"></i> USA receiving address</li><li><i class="fa fa-check text-primary"></i> Shipment forwarding</li><li><i class="fa fa-check text-primary"></i> Tracking updates</li><li><i class="fa fa-check text-primary"></i> Customer support</li>',
                'button_text' => 'Request Quote',
                'button_link' => '#contact',
                'featured' => false,
                'order' => 1,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Consolidated Shipping',
                'section_title' => 'Shipping Options',
                'section_content' => 'Combine eligible purchases where available and request a consolidated shipping quote before dispatch.',
                'price' => 'Quote',
                'interval' => 'Per Shipment',
                'features' => '<li><i class="fa fa-check text-primary"></i> Multiple eligible packages</li><li><i class="fa fa-check text-primary"></i> Consolidation request</li><li><i class="fa fa-check text-primary"></i> Shipment tracking</li><li><i class="fa fa-check text-primary"></i> Delivery to Pakistan</li>',
                'button_text' => 'Request Quote',
                'button_link' => '#contact',
                'featured' => true,
                'order' => 2,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Business & Bulk Shipping',
                'section_title' => 'Shipping Options',
                'section_content' => 'Businesses and bulk importers can contact US2PK for a shipment-specific quotation and logistics requirements.',
                'price' => 'Custom',
                'interval' => 'Contact',
                'features' => '<li><i class="fa fa-check text-primary"></i> Shipment-specific quotation</li><li><i class="fa fa-check text-primary"></i> Bulk and commercial inquiries</li><li><i class="fa fa-check text-primary"></i> Logistics coordination</li><li><i class="fa fa-check text-primary"></i> Customs and delivery guidance</li>',
                'button_text' => 'Contact Sales',
                'button_link' => '#contact',
                'featured' => false,
                'order' => 3,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 7. FAQS (12 entries)
        // ============================================================
        DB::table('faqs')->insert([
            [
                'question' => 'What is US2PK?',
                'answer' => 'US2PK is a USA-to-Pakistan delivery service. Public company coverage describes it as a private firm established in 2013 and associated with Paradise Ecommerce Solutions (PES). Its service model allows customers in Pakistan to shop from US online stores and forward eligible purchases to Pakistan.',
                'section_title' => 'Frequently Asked Questions',
                'section_content' => 'Answers about US2PK, USA shopping, receiving, forwarding, tracking, and delivery to Pakistan.',
                'order' => 1,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'When was US2PK established?',
                'answer' => 'US2PK was established in 2013, according to public company coverage published in 2018.',
                'section_title' => null,
                'section_content' => null,
                'order' => 2,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Where is the US2PK warehouse?',
                'answer' => 'Public descriptions of US2PK identify a warehouse operation in Delaware, USA. Online purchases are described as being received there before shipment to Pakistan.',
                'section_title' => null,
                'section_content' => null,
                'order' => 3,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I shop from US stores using US2PK?',
                'answer' => 'Yes. The documented US2PK service model is designed for customers in Pakistan to shop from US online stores such as Amazon and eBay, send eligible purchases to the US2PK receiving address, and then arrange forwarding to Pakistan.',
                'section_title' => null,
                'section_content' => null,
                'order' => 4,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'How does US2PK delivery work?',
                'answer' => 'Create an account, use your assigned US receiving address when shopping online, have the eligible purchase delivered to the US2PK receiving location, and then arrange forwarding to Pakistan. Tracking information is provided for shipments after dispatch.',
                'section_title' => null,
                'section_content' => null,
                'order' => 5,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Does US2PK provide shipment tracking?',
                'answer' => 'Yes. Public coverage of the service describes shipment tracking and status updates while a package is being transported from the United States to Pakistan.',
                'section_title' => null,
                'section_content' => null,
                'order' => 6,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Where does US2PK deliver in Pakistan?',
                'answer' => 'Public company coverage describes US2PK as operating nationwide in Pakistan. Delivery availability, carrier selection, and service conditions can vary by destination.',
                'section_title' => null,
                'section_content' => null,
                'order' => 7,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'How much does USA-to-Pakistan shipping cost?',
                'answer' => 'Shipping cost depends on the shipment, including service type, weight, dimensions, destination, and any applicable customs or carrier charges. Contact US2PK for a current quotation rather than relying on an outdated fixed price.',
                'section_title' => null,
                'section_content' => null,
                'order' => 8,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Are customs duties included in the shipping price?',
                'answer' => 'Customs duties, taxes, and regulatory charges can depend on the goods, declared value, classification, and applicable Pakistan import rules. Confirm the applicable charges for your shipment before dispatch.',
                'section_title' => null,
                'section_content' => null,
                'order' => 9,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Can I combine multiple purchases into one shipment?',
                'answer' => 'Package consolidation can be requested for eligible purchases where the service and shipment conditions allow it. Consolidation can reduce duplicated international shipping costs, but the actual saving depends on package size, weight, and carrier rules.',
                'section_title' => null,
                'section_content' => null,
                'order' => 10,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Which US stores can I shop from?',
                'answer' => 'US2PK is intended for shopping from US online retailers. Public coverage specifically mentions widely recognized US stores such as Amazon and eBay. Retailer shipping policies and product restrictions still apply.',
                'section_title' => null,
                'section_content' => null,
                'order' => 11,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'What items cannot be shipped?',
                'answer' => 'Restricted and prohibited items can include weapons, explosives, narcotics, hazardous materials, certain batteries, restricted medicines, counterfeit goods, and other items prohibited by carrier, US export, or Pakistan import rules. Always verify an item before purchasing or shipping it.',
                'section_title' => null,
                'section_content' => null,
                'order' => 12,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 8. BLOG POSTS (5 entries)
        // ============================================================
        DB::table('blog_posts')->insert([
            [
                'title' => 'Top 10 Tips for Importing Goods to Pakistan',
                'slug' => 'top-10-tips-importing-goods-pakistan',
                'excerpt' => 'Importing goods to Pakistan can be challenging if you don\'t know the regulations. In this comprehensive guide, we share expert insights on customs clearance, duty calculation, packaging best practices, and common pitfalls to avoid.',
                'content' => '<p>Importing goods to Pakistan can be challenging if you don\'t know the regulations. In this comprehensive guide, we share expert insights on customs clearance, duty calculation, packaging best practices, and common pitfalls to avoid.</p><p>Key topics covered include: understanding HS codes, calculating import duties, choosing the right freight option, preparing documentation, and working with customs brokers. Whether you\'re a first-time importer or an experienced business owner, these tips will help you save time and money.</p>',
                'image' => 'blog/import-tips.jpg',
                'section_title' => 'Latest Articles',
                'section_content' => 'Stay updated with the latest news, tips, and insights from the logistics industry.',
                'published_at' => now()->subDays(15),
                'author' => 'US2PK Logistics Team',
                'order' => 1,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Air Freight vs Sea Freight: Which is Right for You?',
                'slug' => 'air-freight-vs-sea-freight',
                'excerpt' => 'Choosing between air and sea freight depends on your budget, timeline, and cargo type. This comprehensive guide compares both options to help you make an informed decision for your shipment from the USA to Pakistan.',
                'content' => '<p>Choosing between air and sea freight depends on your budget, timeline, and cargo type. This comprehensive guide compares both options to help you make an informed decision for your shipment from the USA to Pakistan.</p><p>We cover: delivery times, cost considerations, cargo types, packaging requirements, and customs clearance differences. Use this guide to optimize your shipping strategy and save money while ensuring reliable delivery.</p>',
                'image' => 'blog/air-vs-sea.jpg',
                'section_title' => null,
                'section_content' => null,
                'published_at' => now()->subDays(10),
                'author' => 'US2PK Logistics Team',
                'order' => 2,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How to Save Money on International Shipping',
                'slug' => 'save-money-international-shipping',
                'excerpt' => 'International shipping doesn\'t have to be expensive. Learn about consolidation, forward planning, seasonal trends, and packaging optimization that can help you cut costs without compromising on reliability.',
                'content' => '<p>International shipping doesn\'t have to be expensive. Learn about consolidation, forward planning, seasonal trends, and packaging optimization that can help you cut costs without compromising on reliability.</p><p>Topics include: package consolidation benefits, choosing the right shipping method, timing your shipments, negotiating rates, and using professional repackaging services. Start saving on your US to Pakistan shipments today.</p>',
                'image' => 'blog/save-money.jpg',
                'section_title' => null,
                'section_content' => null,
                'published_at' => now()->subDays(5),
                'author' => 'US2PK Logistics Team',
                'order' => 3,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Understanding Pakistan Customs Regulations for Imports',
                'slug' => 'pakistan-customs-regulations-imports',
                'excerpt' => 'Navigating Pakistan\'s customs regulations can be complex. This guide provides an overview of key regulations, documentation requirements, and common challenges when importing goods into Pakistan.',
                'content' => '<p>Navigating Pakistan\'s customs regulations can be complex. This guide provides an overview of key regulations, documentation requirements, and common challenges when importing goods into Pakistan.</p><p>Learn about: required import documentation, duty and tax calculations, prohibited and restricted items, temporary import procedures, and customs valuation methods. Our team of customs experts can help you navigate these regulations smoothly.</p>',
                'image' => 'blog/customs-regulations.jpg',
                'section_title' => null,
                'section_content' => null,
                'published_at' => now()->subDays(8),
                'author' => 'US2PK Customs Team',
                'order' => 4,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Ultimate Guide to E-commerce Fulfillment from USA to Pakistan',
                'slug' => 'ecommerce-fulfillment-usa-pakistan',
                'excerpt' => 'E-commerce businesses need efficient fulfillment solutions. This guide covers everything from inventory management to last-mile delivery for online businesses shipping from USA to Pakistan.',
                'content' => '<p>E-commerce businesses need efficient fulfillment solutions. This guide covers everything from inventory management to last-mile delivery for online businesses shipping from USA to Pakistan.</p><p>Key areas covered: inventory management, order processing, warehousing solutions, shipping optimization, and customer experience. Let US2PK help you scale your e-commerce business with reliable shipping solutions.</p>',
                'image' => 'blog/ecommerce-fulfillment.jpg',
                'section_title' => null,
                'section_content' => null,
                'published_at' => now()->subDays(3),
                'author' => 'US2PK Logistics Team',
                'order' => 5,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 9. WHY US SECTIONS (3 entries with features)
        // ============================================================
        DB::table('why_us_sections')->insert([
            [
                'title' => 'Why Choose US2PK',
                'content' => 'We understand the challenges of shipping from the USA to Pakistan. Our expertise, network, and commitment to customer satisfaction set us apart. With thousands of successful shipments delivered, we are the trusted choice for individuals and businesses alike.',
                'image' => 'whyus/why-choose-us-1.jpg',
                'features' => json_encode([
                    'Transparent pricing with no hidden fees',
                    'Real‑time tracking from pickup to delivery',
                    'Expert customs clearance support',
                    'Secure packaging and consolidation services',
                    'Dedicated account managers for businesses',
                    '24/7 multilingual customer support',
                    'Door-to-door delivery across Pakistan',
                    'Secure warehousing and inventory management',
                    'Business logistics and supply chain solutions',
                    'Competitive rates with premium service quality'
                ]),
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'What Sets US2PK Apart',
                'content' => 'US2PK stands out in the logistics industry through our unwavering commitment to customer satisfaction, technological innovation, and operational excellence. We combine years of industry experience with modern technology to deliver a shipping experience that is fast, reliable, and affordable.',
                'image' => 'whyus/why-choose-us-2.jpg',
                'features' => json_encode([
                    'Advanced tracking technology with real-time updates',
                    'Professional consolidation and repackaging services',
                    'Dedicated customs brokerage team with expert knowledge',
                    'Flexible shipping options for every budget',
                    'Personalized service with dedicated account managers',
                    'Quality assurance at every step of the shipping process',
                    'Competitive pricing with volume discounts',
                    'Trusted by leading e-commerce businesses',
                    'Comprehensive insurance coverage options',
                    'Sustainable shipping practices and packaging'
                ]),
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Your Success is Our Priority',
                'content' => 'At US2PK, we believe that your success is our success. Whether you are an individual sending a personal package or a business importing goods, we treat every shipment with the same level of care and professionalism. Our team is dedicated to ensuring your packages arrive safely and on time, every time.',
                'image' => 'whyus/why-choose-us-3.jpg',
                'features' => json_encode([
                    'Customer-first approach with 24/7 support',
                    'Seamless shipping experience from start to finish',
                    'Competitive rates with no compromise on quality',
                    'Trusted partner for individuals and businesses',
                    'Continuous improvement and innovation',
                    'Transparent communication throughout the shipping journey',
                    'Flexible solutions tailored to your needs',
                    'Commitment to on-time delivery',
                    'Secure handling of all packages',
                    'Building lasting relationships with our customers'
                ]),
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 10. CONTACT SECTIONS (1 entry)
        // ============================================================
        DB::table('contact_sections')->insert([
            [
                'title' => 'Request A Free Quote!',
                'subtitle' => 'Get In Touch',
                'content' => 'Tell us what you need and we\'ll give you a competitive price – no obligation. Our logistics experts are ready to assist you with all your shipping needs from the USA to Pakistan.',
                'phone' => '+92 301 5579810',
                'email' => 'admin@us2pk.com',
                'address' => 'Lahore, Pakistan',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 11. FOOTER SECTIONS (1 entry)
        // ============================================================
        DB::table('footer_sections')->insert([
            [
                'title' => 'US2PK',
                'address' => 'Lahore, Pakistan',
                'phone' => '+92 301 5579810',
                'email' => 'admin@us2pk.com',
                'whatsapp_number' => '923015579810',
                'copyright' => '© ' . date('Y') . ' US2PK. All rights reserved.',
                'newsletter_text' => 'Connecting Pakistan to the world\'s best products through trusted shopping, shipping, and delivery.',
                'social_icons' => json_encode([
                    ['platform' => 'facebook', 'url' => 'https://www.facebook.com/profile.php?id=61591958188843', 'icon' => 'fab fa-facebook-f'],
                    ['platform' => 'instagram', 'url' => 'https://instagram.com/us2pk', 'icon' => 'fab fa-instagram'],
                    ['platform' => 'linkedin', 'url' => 'https://linkedin.com/company/us2pk', 'icon' => 'fab fa-linkedin-in'],
                    ['platform' => 'youtube', 'url' => 'https://youtube.com/us2pk', 'icon' => 'fab fa-youtube'],
                ]),
                'service_links' => json_encode([
                    ['title' => 'Air Freight', 'url' => '#services'],
                    ['title' => 'Ocean Freight', 'url' => '#services'],
                    ['title' => 'Customs Clearance', 'url' => '#services'],
                    ['title' => 'Package Consolidation', 'url' => '#services'],
                    ['title' => 'Warehousing & Storage', 'url' => '#services'],
                    ['title' => 'Door‑to‑Door Delivery', 'url' => '#services'],
                ]),
                'company_links' => json_encode([
                    ['title' => 'About Us', 'url' => '/about'],
                    ['title' => 'Contact Us', 'url' => '/contact'],
                    ['title' => 'Team', 'url' => '/team'],
                    ['title' => 'Blog', 'url' => '/blog'],
                ]),
                'quick_links' => json_encode([
                    ['title' => 'FAQs', 'url' => '/faq'],
                    ['title' => 'Pricing', 'url' => '/pricing'],
                    ['title' => 'Prohibited Items', 'url' => '/prohibited-items'],
                    ['title' => 'Sign In', 'url' => '/signin'],
                    ['title' => 'Register', 'url' => '/signup'],
                ]),
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 12. STATISTICS / COMPANY FACTS (3 entries)
        // ============================================================
        DB::table('stats')->insert([
            [
                'happy_clients' => 18400,
                'complete_shipments' => 54900,
                'customer_reviews' => 4.8,
                'active_services' => 12,
                'section_title' => 'US2PK Since 2013',
                'section_content' => 'US2PK was established in 2013 and has been publicly described as a USA-to-Pakistan delivery service with a Delaware receiving/warehouse operation and nationwide delivery in Pakistan.',
                'phone' => '+92 301 5579810',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'happy_clients' => 25000,
                'complete_shipments' => 75000,
                'customer_reviews' => 4.9,
                'active_services' => 15,
                'section_title' => 'Our Growth Story',
                'section_content' => 'Growing rapidly with expanding services and reaching more cities across Pakistan every day.',
                'phone' => '+92 301 5579810',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'happy_clients' => 32000,
                'complete_shipments' => 95000,
                'customer_reviews' => 4.7,
                'active_services' => 18,
                'section_title' => 'Our Impact',
                'section_content' => 'Making international shipping accessible to everyone with our expanding network and services.',
                'phone' => '+92 301 5579810',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 13. PROHIBITED ITEMS (27 entries - Complete from US2PK)
        // ============================================================
        DB::table('prohibited_items')->insert([
            [
                'item_name' => 'Firearms and Ammunition',
                'category' => 'Weapons',
                'description' => 'All types of firearms, guns, pistols, rifles, and ammunition.',
                'reason' => 'Strictly prohibited by Pakistan customs regulations and international shipping laws.',
                'severity' => 'high',
                'icon' => 'fas fa-gun',
                'is_active' => true,
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Illegal Drugs and Narcotics',
                'category' => 'Drugs',
                'description' => 'Any form of illegal drugs, narcotics, or controlled substances.',
                'reason' => 'Violation of international drug trafficking laws and Pakistan customs regulations.',
                'severity' => 'high',
                'icon' => 'fas fa-skull',
                'is_active' => true,
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Explosives and Fireworks',
                'category' => 'Hazardous Materials',
                'description' => 'Fireworks, explosives, blasting caps, and other explosive materials.',
                'reason' => 'Poses serious safety and security risks during transportation.',
                'severity' => 'high',
                'icon' => 'fas fa-bomb',
                'is_active' => true,
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Perishable Food Items',
                'category' => 'Perishable Goods',
                'description' => 'Fresh fruits, vegetables, meat, dairy, and other perishable foods.',
                'reason' => 'Risk of spoilage and contamination during transit.',
                'severity' => 'medium',
                'icon' => 'fas fa-apple-alt',
                'is_active' => true,
                'order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Counterfeit Goods',
                'category' => 'Illegal Items',
                'description' => 'Fake branded products, counterfeit currency, and pirated items.',
                'reason' => 'Violation of intellectual property laws and customs regulations.',
                'severity' => 'high',
                'icon' => 'fas fa-copyright',
                'is_active' => true,
                'order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Flammable Liquids',
                'category' => 'Hazardous Materials',
                'description' => 'Gasoline, paint thinner, alcohol, and other flammable liquids.',
                'reason' => 'Fire hazard during transportation and storage.',
                'severity' => 'high',
                'icon' => 'fas fa-fire',
                'is_active' => true,
                'order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Corrosive Chemicals',
                'category' => 'Hazardous Materials',
                'description' => 'Acids, alkalis, and other corrosive substances.',
                'reason' => 'Can cause damage to other cargo and harm handlers.',
                'severity' => 'high',
                'icon' => 'fas fa-flask',
                'is_active' => true,
                'order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Lithium Batteries',
                'category' => 'Electronics',
                'description' => 'Loose lithium batteries and power banks.',
                'reason' => 'Fire risk during air transportation.',
                'severity' => 'medium',
                'icon' => 'fas fa-battery-full',
                'is_active' => true,
                'order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Radioactive Materials',
                'category' => 'Hazardous Materials',
                'description' => 'Any radioactive substances or materials.',
                'reason' => 'Extreme health and safety hazards.',
                'severity' => 'high',
                'icon' => 'fas fa-radiation',
                'is_active' => true,
                'order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Live Animals',
                'category' => 'Live Animals',
                'description' => 'Live animals, birds, reptiles, and insects.',
                'reason' => 'Strict quarantine and health regulations.',
                'severity' => 'medium',
                'icon' => 'fas fa-paw',
                'is_active' => true,
                'order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Pornographic Materials',
                'category' => 'Illegal Items',
                'description' => 'Obscene or pornographic content in any form.',
                'reason' => 'Violation of Pakistan content laws.',
                'severity' => 'high',
                'icon' => 'fas fa-ban',
                'is_active' => true,
                'order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Currency and Monetary Instruments',
                'category' => 'Currency',
                'description' => 'Large amounts of cash, traveler\'s checks, and bearer bonds.',
                'reason' => 'Subject to strict financial regulations.',
                'severity' => 'medium',
                'icon' => 'fas fa-money-bill-wave',
                'is_active' => true,
                'order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Combustible & Flammable Items',
                'category' => 'Hazardous Materials',
                'description' => 'Combustible & Flammable Items - Easily ignitable items such as paints, oils, lighters, perfumes and nail polish.',
                'reason' => 'Fire hazard during transportation and storage.',
                'severity' => 'high',
                'icon' => 'fas fa-fire-extinguisher',
                'is_active' => true,
                'order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Uninstalled Lithium-Ion Batteries',
                'category' => 'Batteries',
                'description' => 'Standalone lithium-ion batteries that may pose fire and transport risks.',
                'reason' => 'Fire risk during air transportation and potential short-circuit hazards.',
                'severity' => 'high',
                'icon' => 'fas fa-bolt',
                'is_active' => true,
                'order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Pressurized Cans & Aerosols',
                'category' => 'Hazardous Materials',
                'description' => 'Pressurized products such as hair spray, shaving cream and aerosol cans.',
                'reason' => 'Risk of explosion or combustion under pressure changes during transit.',
                'severity' => 'high',
                'icon' => 'fas fa-spray-can',
                'is_active' => true,
                'order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Firearms, Weapons & Weapon Parts',
                'category' => 'Weapons',
                'description' => 'Firearms, ammunition, weapon parts, replicas and tactical equipment.',
                'reason' => 'Strictly prohibited by Pakistan customs regulations and international arms laws.',
                'severity' => 'high',
                'icon' => 'fas fa-crosshairs',
                'is_active' => true,
                'order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Tobacco, Plants & Seeds',
                'category' => 'Agricultural Products',
                'description' => 'Tobacco, plants, seeds and other agricultural products subject to restrictions.',
                'reason' => 'Subject to strict agricultural and quarantine regulations.',
                'severity' => 'high',
                'icon' => 'fas fa-seedling',
                'is_active' => true,
                'order' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Coffee',
                'category' => 'Food & Beverages',
                'description' => 'Coffee products that may require additional customs review or documentation.',
                'reason' => 'May require additional customs review and specific documentation.',
                'severity' => 'medium',
                'icon' => 'fas fa-coffee',
                'is_active' => true,
                'order' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Animals & Animal Skin/Fur Products',
                'category' => 'Restricted Goods',
                'description' => 'Animals and products containing animal skin, fur or other restricted materials.',
                'reason' => 'Strict quarantine and wildlife protection regulations apply.',
                'severity' => 'high',
                'icon' => 'fas fa-paw',
                'is_active' => true,
                'order' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Alcohol',
                'category' => 'Restricted Goods',
                'description' => 'Alcoholic beverages and alcohol-based products restricted by shipping regulations.',
                'reason' => 'Strictly regulated or prohibited by Pakistan customs and import laws.',
                'severity' => 'high',
                'icon' => 'fas fa-wine-bottle',
                'is_active' => true,
                'order' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Cash, Currency & Valuable Financial Items',
                'category' => 'Financial Items',
                'description' => 'Cash, currency, money orders, bonds and other financial instruments.',
                'reason' => 'Subject to strict financial regulations and anti-money laundering laws.',
                'severity' => 'high',
                'icon' => 'fas fa-money-bill',
                'is_active' => true,
                'order' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Jewelry & Precious Stones',
                'category' => 'Valuable Items',
                'description' => 'Valuable jewelry and precious stones subject to country and insurance limits.',
                'reason' => 'Subject to country-specific limits and insurance valuation requirements.',
                'severity' => 'medium',
                'icon' => 'fas fa-gem',
                'is_active' => true,
                'order' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Lottery Tickets & Gambling Devices',
                'category' => 'Restricted Goods',
                'description' => 'Lottery tickets, gambling devices and related restricted items.',
                'reason' => 'Prohibited or restricted by gambling laws in many jurisdictions.',
                'severity' => 'high',
                'icon' => 'fas fa-dice',
                'is_active' => true,
                'order' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Prescription & Veterinary Medication',
                'category' => 'Medicines',
                'description' => 'Prescription medicines and veterinary drugs that may require authorization.',
                'reason' => 'Requires proper authorization and may be subject to strict regulations.',
                'severity' => 'high',
                'icon' => 'fas fa-prescription-bottle',
                'is_active' => true,
                'order' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Pornography',
                'category' => 'Restricted Content',
                'description' => 'Sexually explicit or pornographic materials prohibited or restricted by law.',
                'reason' => 'Violation of Pakistan content laws and international obscenity regulations.',
                'severity' => 'high',
                'icon' => 'fas fa-ban',
                'is_active' => true,
                'order' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Lock Picking Devices',
                'category' => 'Security Tools',
                'description' => 'Tools designed to pick, bypass or defeat locks and security systems.',
                'reason' => 'Restricted as potential security threats and illegal in many jurisdictions.',
                'severity' => 'high',
                'icon' => 'fas fa-lock-open',
                'is_active' => true,
                'order' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Government IDs, Licenses & Official-Looking Items',
                'category' => 'Government Documents',
                'description' => 'Government IDs, licenses, badges, uniforms or items resembling official documents.',
                'reason' => 'Potential for fraud and identity theft; restricted by law.',
                'severity' => 'high',
                'icon' => 'fas fa-id-card',
                'is_active' => true,
                'order' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ============================================================
        // 14. QUOTE REQUESTS (3 entries - for demonstration)
        // ============================================================
        DB::table('quote_requests')->insert([
            [
                'name' => 'Muhammad Hassan',
                'email' => 'hassan@example.com',
                'mobile' => '+92 300 1234567',
                'service' => 'Air Freight',
                'note' => 'I need to ship electronics from New York to Lahore. Please provide a quote for 50kg shipment.',
                'status' => 'pending',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'name' => 'Fatima Ahmed',
                'email' => 'fatima@example.com',
                'mobile' => '+92 301 7654321',
                'service' => 'Ocean Freight',
                'note' => 'I want to import furniture from Los Angeles to Karachi. Need FCL container pricing.',
                'status' => 'contacted',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(3),
            ],
            [
                'name' => 'Ali Raza',
                'email' => 'ali@example.com',
                'mobile' => '+92 302 9876543',
                'service' => 'Customs Clearance',
                'note' => 'I need help with customs clearance for my shipment that just arrived. Please assist.',
                'status' => 'completed',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(8),
            ],
        ]);
    }
}
